// Generated by naga HLSL backend
// Target: SM 5.1

static const uint DATA_SIZE = 8u;

float sum_array(float[4] arr) {
    float total = 0.0;
    uint i = 0u;
    
    [loop]
    while (true) {
        if (!((i < 4u))) {
            break;
        }
        total = (total + arr[i]);
        // continuing
        i = (i + 1u);
    }
    return total;
}

[numthreads(1, 1, 1)]
void cs_main() {
    uint data[4];
    uint idx = 2u;
    
    float _e4[4] = {1.0, 2.0, 3.0, 4.0};
    int _e8[3] = {10, 20, 30};
    float2 _e15[2] = {float2(1.0, 2.0), float2(3.0, 4.0)};
    float _e17 = _e4[0];
    float _e19 = _e4[3];
    float _e22 = _e15[1].y;
    data[0] = 100u;
    data[1] = 200u;
    data[2] = (data[0] + data[1]);
    data[3] = (data[2] * 2u);
    uint _e45 = data[idx];
    float _cr46 = sum_array(_e4);
}

