// Generated by naga HLSL backend
// Target: SM 5.1

groupshared uint shared_counter;
RWStructuredBuffer<uint[]> result : register(u0, space0);

struct cs_main_Input {
    uint lid : SV_GroupIndex;
};

[numthreads(64, 1, 1)]
void cs_main(cs_main_Input _input, uint lid : SV_GroupIndex) {
    
    if ((lid == 0u)) {
        InterlockedExchange(shared_counter, 0u);
    }
    GroupMemoryBarrierWithGroupSync();
    InterlockedAdd(shared_counter, 1u, _atomic_result);
    GroupMemoryBarrierWithGroupSync();
    if ((lid == 0u)) {
        InterlockedExchange(shared_counter, shared_counter, _atomic_result);
        result[0] = _atomic_result;
    }
}

