// Generated by naga HLSL backend
// Target: SM 5.1

struct Data {
    uint values[];
};

RWStructuredBuffer<Data> data_1 : register(u0, space0);

uint collatz_iterations(uint n_base) {
    uint n = n_base;
    uint i = 0u;
    
    [loop]
    while (true) {
        if (!((n > 1u))) {
            break;
        }
        if (((n % 2u) == 0u)) {
            n = (n / 2u);
        } else {
            {
                n = ((3u * n) + 1u);
            }
        }
        i = (i + 1u);
    }
    return i;
}

struct cs_main_Input {
    uint3 gid : SV_DispatchThreadID;
};

[numthreads(64, 1, 1)]
void cs_main(cs_main_Input _input, uint3 gid : SV_DispatchThreadID) {
    
    uint _cr9 = collatz_iterations(data_1.values[gid.x]);
    data_1.values[gid.x] = _cr9;
}

