// Generated by naga HLSL backend
// Target: SM 5.1

struct cs_main_Input {
    uint3 id : SV_DispatchThreadID;
};

[numthreads(64, 1, 1)]
void cs_main(cs_main_Input _input, uint3 id : SV_DispatchThreadID) {
    uint x = (id.x * 2u);
    
}

