// Generated by naga HLSL backend
// Target: SM 5.1

struct Foo {
    float4 a;
    int b;
};

[numthreads(1, 1, 1)]
void cs_main() {
    Foo foo_1;
    
    foo_1 = Foo(float4(1.0, 1.0, 1.0, 1.0), 1);
    float2x2 _e9 = float2x2(1.0, 0.0, 0.0, 1.0);
    bool _e10 = bool();
    int _e11 = int();
    uint _e12 = uint();
    float _e13 = float();
    uint2 _e14 = uint2();
    uint2 _e16 = uint2(0u, 0u);
    float2x2 _e21 = float2x2(float2(0.0, 0.0), float2(0.0, 0.0));
    int _e26[4] = {0, 1, 2, 3};
    int _e28 = (int)(1u);
    float _e30 = (float)(1);
    uint _e32 = (uint)(true);
}

