// Generated by naga HLSL backend
// Target: SM 5.1

[numthreads(1, 1, 1)]
void cs_main() {
    float _e1 = (float)(42u);
    float _e4 = (float)(-(7));
    uint _e6 = (uint)(3.14);
    int _e8 = (int)(2.71);
    uint _e10 = (uint)(10);
    int _e12 = (int)(10u);
    bool _e14 = (bool)(1);
    bool _e16 = (bool)(0u);
    int _e18 = (int)(true);
    uint _e20 = (uint)(false);
    float _e22 = (float)(true);
    float3 _e27 = (float)(uint3(1u, 2u, 3u));
    uint3 _e32 = (uint)(float3(1.5, 2.5, 3.5));
    int3 _e37 = (int)(float3(1.0, 2.0, 3.0));
    float _e39 = asuint(0.0);
    float _e40 = asfloat(_e39);
    float4 _e46 = asuint(float4(1.0, 2.0, 3.0, 4.0));
}

