// Generated by naga HLSL backend
// Target: SM 5.1

[numthreads(1, 1, 1)]
void cs_main() {
    float _e0 = 1.0;
    float _e1 = 2.0;
    float _e2 = 3.0;
    float _e3 = 4.0;
    float _e6 = ((_e0 * _e1) + (_e2 * _e3));
    float _e9 = ((_e0 + _e1) * (_e2 - _e3));
    float _e12 = ((_e0 / _e1) - (_e2 / _e3));
    float _e15 = (((_e0 + _e1) + _e2) * _e3);
    float _e17 = (true ? _e1 : _e0);
    float3 _e23 = (false ? float3(1.0, 1.0, 1.0) : float3(0.0, 0.0, 0.0));
    int _e27 = ((_e0 > _e1) ? 20 : 10);
    float3 _e28 = float3(_e0, _e1, _e2);
    float3 _e29 = float3(_e3, _e2, _e1);
    float3 _e33 = ((_e28 * _e29) + float3(1.0, 1.0, 1.0));
    float _e36 = (length(_e28) * dot(_e28, _e29));
    float3 _e38 = normalize((_e28 + _e29));
}

