// Generated by naga HLSL backend
// Target: SM 5.1

struct ps_main_Input {
    float4 color : TEXCOORD0;
};

float4 ps_main(ps_main_Input _input) : SV_Target0 {
    float4 color = _input.color;
    
    return color;
}

