// Generated by naga HLSL backend
// Target: SM 5.1

float add(float a, float b) {
    return (a + b);
}

float2 multiply(float2 a, float2 b) {
    return (a * b);
}

float2 test_fma() {
    float2 _e2 = float2(2.0, 2.0);
    float2 _e5 = float2(0.5, 0.5);
    float2 _e8 = float2(0.5, 0.5);
    return mad(_e2, _e5, _e8);
}

[numthreads(1, 1, 1)]
void cs_main() {
    float _cr2 = add(1.0, 2.0);
    float2 _cr9 = multiply(float2(2.0, 3.0), float2(4.0, 5.0));
    float2 _cr10 = test_fma();
}

