// Generated by naga HLSL backend
// Target: SM 5.1

struct Uniforms {
    float4 color;
    float scale;
};

cbuffer uniforms_1_cbuffer : register(b0, space0) {
    Uniforms uniforms_1;
};
groupshared float[64] shared_data;

struct cs_main_Input {
    uint local_idx : SV_GroupIndex;
};

[numthreads(64, 1, 1)]
void cs_main(cs_main_Input _input, uint local_idx : SV_GroupIndex) {
    
    shared_data[local_idx] = (uniforms_1.scale * (float)(local_idx));
    GroupMemoryBarrierWithGroupSync();
    float _e12 = (shared_data[local_idx] + uniforms_1.color.x);
}

