// Generated by naga HLSL backend
// Target: SM 5.1

struct vs_vs_main_Input {
    uint vertex_index : SV_VertexID;
};

float4 vs_vs_main(vs_vs_main_Input _input) : SV_Position {
    uint vertex_index = _input.vertex_index;
    
    float _e3 = ((float)(vertex_index) / 3.0);
    return float4(_e3, 0.0, 0.0, 1.0);
}

struct ps_fs_main_Input {
    float4 color : TEXCOORD0;
};

float4 ps_fs_main(ps_fs_main_Input _input) : SV_Target0 {
    float4 color = _input.color;
    
    return color;
}

