// Generated by naga HLSL backend
// Target: SM 5.1

[numthreads(1, 1, 1)]
void cs_main() {
    float a = 10.0;
    uint counter = 0u;
    int temp = 20;
    float uninit_f;
    uint2 uninit_v;
    
    float _e0 = 1.0;
    float _e1 = 2.0;
    float _e2 = (_e0 + _e1);
    a = (a + 1.0);
    a = (a * 2.0);
    int _e9 = 42;
    uint _e10 = 100u;
    bool _e11 = true;
    float3 _e15 = float3(1.0, 2.0, 3.0);
    counter = (counter + 1u);
    counter = (counter + 1u);
    int _e22 = 10;
    {
        int _e23 = 20;
        temp = (temp + 1);
    }
    uninit_f = 5.0;
    uninit_v = uint2(1u, 2u);
}

