// Generated by naga HLSL backend
// Target: SM 5.1

int nested_loops() {
    int total = 0;
    int i = 0;
    int j = 0;
    
    [loop]
    while (true) {
        if (!((i < 3))) {
            break;
        }
        [loop]
        while (true) {
            if (!((j < 3))) {
                break;
            }
            total = ((total + (i * 3)) + j);
            // continuing
            j = (j + 1);
        }
        // continuing
        i = (i + 1);
    }
    return total;
}

int loop_with_break() {
    int sum = 0;
    int i_1 = 0;
    
    [loop]
    while (true) {
        if ((i_1 >= 10)) {
            break;
        }
        if ((i_1 == 5)) {
            i_1 = (i_1 + 1);
            continue;
        }
        sum = (sum + i_1);
        i_1 = (i_1 + 1);
    }
    return sum;
}

int loop_with_continuing() {
    int sum_2 = 0;
    int i_3 = 0;
    
    [loop]
    while (true) {
        if ((i_3 >= 5)) {
            break;
        }
        sum_2 = (sum_2 + i_3);
        // continuing
        i_3 = (i_3 + 1);
    }
    return sum_2;
}

int while_loop() {
    int n = 100;
    
    [loop]
    while (true) {
        if (!((n > 1))) {
            break;
        }
        n = (n / 2);
    }
    return n;
}

[numthreads(1, 1, 1)]
void cs_main() {
    int _cr0 = nested_loops();
    int _cr1 = loop_with_break();
    int _cr2 = loop_with_continuing();
    int _cr3 = while_loop();
}

