// Generated by naga HLSL backend
// Target: SM 5.1

[numthreads(1, 1, 1)]
void cs_main() {
    float3 _e3 = float3(1.0, 2.0, 3.0);
    float3 _e7 = float3(4.0, 5.0, 6.0);
    float _e8 = 0.5;
    float3 _e9 = normalize(_e3);
    float _e10 = length(_e3);
    float _e11 = dot(_e3, _e7);
    float3 _e12 = cross(_e3, _e7);
    float _e15 = clamp(_e8, 0.0, 1.0);
    float3 _e17 = lerp(_e3, _e7, 0.5);
    float _e20 = smoothstep(0.0, 1.0, _e8);
    float _e23 = abs(-(1.0));
    float _e26 = sign(-(5.0));
    float _e28 = floor(1.7);
    float _e30 = ceil(1.3);
    float _e33 = min(1.0, 2.0);
    float _e36 = max(1.0, 2.0);
    float _e38 = sqrt(4.0);
    float _e41 = pow(2.0, 3.0);
    float _e43 = exp(1.0);
    float _e45 = log(1.0);
}

