// Generated by naga HLSL backend
// Target: SM 5.1

[numthreads(1, 1, 1)]
void cs_main() {
    float4x4 _e16 = float4x4(1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0);
    float2x2 _e21 = float2x2(1.0, 0.0, 0.0, 1.0);
    float3x3 _e31 = float3x3(1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0);
    float4x3 _e44 = float4x3(1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0);
    float4 _e49 = float4(1.0, 2.0, 3.0, 1.0);
    float4 _e50 = mul(_e49, _e16);
    float4x4 _e51 = mul(_e16, _e16);
    float2x2 _e52 = transpose(_e21);
    float4 _e54 = _e16[0];
    float4 _e56 = _e16[1];
    float _e60 = _e16[2][3];
    float2x2 _e62 = mul(2.0, _e21);
}

