// Generated by naga HLSL backend
// Target: SM 5.1

struct FragmentOutput {
    float4 color;
    float4 normal;
};

struct vs_vs_main_Input {
    uint vi : SV_VertexID;
};

float4 vs_vs_main(vs_vs_main_Input _input) : SV_Position {
    uint vi = _input.vi;
    
    return float4(0.0, 0.0, 0.0, 1.0);
}

struct ps_fs_main_Input {
    float4 frag_coord : SV_Position;
};

struct ps_fs_main_Output {
    float4 color : SV_Target0;
    float4 normal : SV_Target1;
};

ps_fs_main_Output ps_fs_main(ps_fs_main_Input _input) {
    float4 frag_coord = _input.frag_coord;
    ps_fs_main_Output _output;
    
    _output.color = float4(1.0, 0.0, 0.0, 1.0);
    _output.normal = float4(0.0, 0.0, 1.0, 1.0);
    return _output;
    return _output;
}

