// Generated by naga HLSL backend
// Target: SM 5.1

void arithmetic() {
    int _e0 = 1;
    uint _e1 = 1u;
    float _e2 = 1.0;
    int _e3 = 2;
    uint _e4 = 2u;
    float _e5 = 2.0;
    float _e6 = -(_e2);
    int2 _e8 = -(int2(_e0, _e0));
    int _e9 = (_e3 + _e0);
    uint _e10 = (_e4 + _e1);
    float _e11 = (_e5 + _e2);
    int _e12 = (_e3 - _e0);
    float _e13 = (_e5 * _e2);
    int _e14 = (_e3 / _e0);
    uint _e15 = (_e4 % _e1);
}

void comparison() {
    int _e0 = 1;
    int _e1 = 2;
    bool _e2 = (_e0 == _e1);
    bool _e3 = (_e0 != _e1);
    bool _e4 = (_e0 < _e1);
    bool _e5 = (_e0 <= _e1);
    bool _e6 = (_e0 > _e1);
    bool _e7 = (_e0 >= _e1);
}

void bitwise() {
    int _e0 = 1;
    int _e1 = 2;
    int _e2 = (_e0 | _e1);
    int _e3 = (_e0 & _e1);
    int _e4 = (_e0 ^ _e1);
    int _e5 = ~(_e0);
    int _e7 = (_e0 << 1u);
    int _e9 = (_e1 >> 1u);
}

[numthreads(1, 1, 1)]
void cs_main() {
    float _cr0 = arithmetic();
    float _cr1 = comparison();
    float _cr2 = bitwise();
}

