// Generated by naga HLSL backend
// Target: SM 5.1

struct Data {
    float value;
    uint count;
};

void increment(int p) {
    p = (p + 1);
}

float read_value(float p) {
    return p;
}

void swap(int a, int b) {
    int _e2 = a;
    a = b;
    b = _e2;
}

void modify_array_element(float[4] arr, uint idx, float val) {
    arr[idx] = val;
}

void modify_struct_field(Data d) {
    d.value = (d.value * 2.0);
    d.count = (d.count + 1u);
}

[numthreads(1, 1, 1)]
void cs_main() {
    int x = 10;
    float f = 3.14;
    int a = 1;
    int b = 2;
    float arr[4] = {1.0, 2.0, 3.0, 4.0};
    Data data_1 = Data(1.0, 0u);
    
    float _cr2 = increment(x);
    float _cr3 = increment(x);
    float _cr6 = read_value(f);
    float _cr11 = swap(a, b);
    float _cr20 = modify_array_element(arr, 0u, 99.0);
    float _cr25 = modify_struct_field(data_1);
}

