// Generated by naga HLSL backend
// Target: SM 5.1

struct VertexOutput {
    float4 position;
    float2 uv;
};

struct vs_vs_main_Input {
    uint vi : SV_VertexID;
};

struct vs_vs_main_Output {
    float4 position : SV_Position;
    float2 uv : TEXCOORD0;
};

vs_vs_main_Output vs_vs_main(vs_vs_main_Input _input) {
    uint vi = _input.vi;
    float2 pos;
    float2 uv;
    
    vs_vs_main_Output _output;
    
    float _e10 = (((float)(((int)(vi) / 2)) * 4.0) - 1.0);
    float _e18 = (((float)(((int)(vi) % 2)) * 4.0) - 1.0);
    pos = float2(_e10, _e18);
    uv = ((pos + 1.0) * 0.5);
    return VertexOutput(float4(pos, 0.0, 1.0), uv);
    return _output;
}

struct ps_fs_main_Input {
    float2 uv : TEXCOORD0;
};

float4 ps_fs_main(ps_fs_main_Input _input) : SV_Target0 {
    float2 uv = _input.uv;
    
    return float4(uv, 0.0, 1.0);
}

