// Generated by naga HLSL backend
// Target: SM 5.1

struct Inner {
    float value;
    uint flag;
};

struct Outer {
    float3 position;
    Inner inner;
    float scale;
};

float process_struct(Outer s) {
    return ((s.position.x * s.scale) + s.inner.value);
}

[numthreads(1, 1, 1)]
void cs_main() {
    Outer mutable_outer = Outer(float3(1.0, 2.0, 3.0), Inner(3.14, 1u), 2.0);
    
    Inner _e2 = Inner(3.14, 1u);
    Outer _e8 = Outer(float3(1.0, 2.0, 3.0), _e2, 2.0);
    float3 _e9 = _e8.position;
    float _e11 = _e8.inner.value;
    uint _e13 = _e8.inner.flag;
    mutable_outer.scale = 5.0;
    mutable_outer.inner.value = 42.0;
    float _cr20 = process_struct(mutable_outer);
}

