// Generated by naga HLSL backend
// Target: SM 5.1

[numthreads(1, 1, 1)]
void cs_main() {
    float4 _e4 = float4(1.0, 2.0, 3.0, 4.0);
    float _e5 = _e4.x;
    float _e6 = _e4.y;
    float _e7 = _e4.z;
    float _e8 = _e4.w;
    float2 _e9 = _e4.xy;
    float3 _e10 = _e4.xyz;
    float4 _e11 = _e4.xyzw;
    float2 _e12 = _e4.zw;
    float2 _e13 = _e4.xx;
    float3 _e14 = _e4.yyy;
    float4 _e15 = _e4.wzyx;
    float2 _e16 = _e4.yx;
    float3 _e17 = _e4.zxy;
    float2 _e20 = float2(1.0, 2.0);
    float2 _e21 = _e20.yx;
    float2 _e22 = _e20.xx;
    float3 _e26 = float3(1.0, 2.0, 3.0);
    float2 _e27 = _e26.zx;
    float3 _e28 = _e26.yxz;
}

