// Generated by naga HLSL backend
// Target: SM 5.1

RWTexture2D<float4> output_tex : register(u0, space0);

struct cs_main_Input {
    uint3 gid : SV_DispatchThreadID;
};

[numthreads(8, 8, 1)]
void cs_main(cs_main_Input _input, uint3 gid : SV_DispatchThreadID) {
    
    uint3 _e2 = output_tex.GetDimensions(_dim_w, _dim_h);
    if (((gid.x >= _e2.x) || (gid.y >= _e2.y))) {
        return;
    }
    float2 _e20 = float2(((float)(gid.x) / (float)(_e2.x)), ((float)(gid.y) / (float)(_e2.y)));
    float4 _e25 = float4(_e20.x, _e20.y, 0.5, 1.0);
    output_tex[(int)(gid.xy)] = _e25;
}

