// Generated by naga HLSL backend
// Target: SM 5.1

struct VertexOutput {
    float4 position;
    float2 uv;
};

Texture2D<float4> t_diffuse : register(t0, space0);
SamplerState s_diffuse : register(s1, space0);

struct vs_vs_main_Input {
    uint vi : SV_VertexID;
};

struct vs_vs_main_Output {
    float4 position : SV_Position;
    float2 uv : TEXCOORD0;
};

vs_vs_main_Output vs_vs_main(vs_vs_main_Input _input) {
    uint vi = _input.vi;
    
    vs_vs_main_Output _output;
    
    float _e8 = (((float)(((int)(vi) / 2)) * 4.0) - 1.0);
    float _e16 = (((float)(((int)(vi) % 2)) * 4.0) - 1.0);
    float2 _e17 = float2(_e8, _e16);
    float2 _e21 = ((_e17 + 1.0) * 0.5);
    return VertexOutput(float4(_e17, 0.0, 1.0), _e21);
    return _output;
}

struct ps_fs_main_Input {
    float2 uv : TEXCOORD0;
};

float4 ps_fs_main(ps_fs_main_Input _input) : SV_Target0 {
    float2 uv = _input.uv;
    
    float4 _e3 = t_diffuse.Sample(s_diffuse, uv);
    return _e3;
}

