// Generated by naga HLSL backend
// Target: SM 5.1

struct Uniforms {
    row_major float4x4 model;
    row_major float4x4 view;
    row_major float4x4 projection;
};

struct VertexOutput {
    float4 position;
    float3 world_pos;
};

cbuffer uniforms_1_cbuffer : register(b0, space0) {
    Uniforms uniforms_1;
};

struct vs_vs_main_Input {
    float3 position : TEXCOORD0;
};

struct vs_vs_main_Output {
    float4 position : SV_Position;
    float3 world_pos : TEXCOORD0;
};

vs_vs_main_Output vs_vs_main(vs_vs_main_Input _input) {
    float3 position = _input.position;
    vs_vs_main_Output _output;
    
    float4 _e5 = mul(float4(position, 1.0), uniforms_1.model);
    float4 _e11 = mul(_e5, mul(uniforms_1.view, uniforms_1.projection));
    _output.position = _e11;
    _output.world_pos = _e5.xyz;
    return _output;
    return _output;
}

struct ps_fs_main_Input {
    float3 world_pos : TEXCOORD0;
};

float4 ps_fs_main(ps_fs_main_Input _input) : SV_Target0 {
    float3 world_pos = _input.world_pos;
    
    float3 _e5 = ((normalize(world_pos) * 0.5) + 0.5);
    return float4(_e5, 1.0);
}

