// Generated by naga HLSL backend
// Target: SM 5.1

struct vs_main_Input {
    uint idx : SV_VertexID;
};

float4 vs_main(vs_main_Input _input) : SV_Position {
    uint idx = _input.idx;
    
    return float4(0.0, 0.0, 0.0, 1.0);
}

