// Generated by naga HLSL backend
// Target: SM 5.1

struct VertexInput {
    float3 position;
    float3 color;
};

struct VertexOutput {
    float4 position;
    float3 color;
};

struct vs_vs_main_Input {
    float3 position : TEXCOORD0;
    float3 color : TEXCOORD1;
};

struct vs_vs_main_Output {
    float4 position : SV_Position;
    float3 color : TEXCOORD0;
};

vs_vs_main_Output vs_vs_main(vs_vs_main_Input _input) {
    VertexInput _in;
    _in.position = _input.position;
    _in.color = _input.color;
    vs_vs_main_Output _output;
    
    _output.position = float4(_in.position, 1.0);
    _output.color = _in.color;
    return _output;
    return _output;
}

struct ps_fs_main_Input {
    float3 color : TEXCOORD0;
};

float4 ps_fs_main(ps_fs_main_Input _input) : SV_Target0 {
    float3 color = _input.color;
    
    return float4(color, 1.0);
}

