// Generated by naga HLSL backend
// Target: SM 5.1

struct Params {
    uint count;
};

groupshared float[256] shared_data;
cbuffer params_1_cbuffer : register(b0, space0) {
    Params params_1;
};
RWStructuredBuffer<float[]> output : register(u1, space0);

struct cs_main_Input {
    uint lid : SV_GroupIndex;
    uint3 gid : SV_DispatchThreadID;
};

[numthreads(256, 1, 1)]
void cs_main(cs_main_Input _input, uint lid : SV_GroupIndex, uint3 gid : SV_DispatchThreadID) {
    
    shared_data[lid] = ((float)(gid.x) * 0.5);
    GroupMemoryBarrierWithGroupSync();
    if ((lid < 128u)) {
        shared_data[lid] = (shared_data[lid] + shared_data[(lid + 128u)]);
    }
    GroupMemoryBarrierWithGroupSync();
    if ((lid == 0u)) {
        output[(gid.x / 256u)] = shared_data[0];
    }
}

