# GolangCI-Lint v2.10 Configuration for Naga - Pure Go Shader Compiler
# Documentation: https://golangci-lint.run/docs/configuration/

version: "2"

run:
  timeout: 5m
  tests: true

linters:
  # Enable standard set plus extras
  enable:
    # Code quality
    - gocyclo
    - gocognit
    - funlen
    - maintidx
    - cyclop
    - nestif

    # Bug detection
    - govet
    - staticcheck
    - errcheck
    - errorlint
    - gosec
    - nilnil
    - nilerr
    - ineffassign

    # Code style
    - misspell
    - whitespace
    - unconvert
    - unparam

    # Naming
    - errname
    - revive

    # Performance
    - prealloc
    - makezero

    # Code practices
    - goconst
    - gocritic
    - goprintffuncname
    - nolintlint
    - nakedret

    # Additional
    - dupl
    - dogsled
    - durationcheck

  settings:
    govet:
      enable:
        - copylocks
      disable:
        - fieldalignment

    gocyclo:
      min-complexity: 20

    cyclop:
      max-complexity: 20

    funlen:
      lines: 120
      statements: 60

    gocognit:
      min-complexity: 30

    misspell:
      locale: US

    nestif:
      min-complexity: 4

    revive:
      rules:
        - name: var-naming
        - name: error-return
        - name: error-naming
        - name: if-return
        - name: increment-decrement
        - name: var-declaration
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unreachable-code
        - name: redefines-builtin-id

    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance

      disabled-checks:
        - commentFormatting
        - whyNoLint
        - unnamedResult
        - commentedOutCode
        - octalLiteral
        - paramTypeCombine

      settings:
        hugeParam:
          sizeThreshold: 256

  exclusions:
    rules:
      # Test files - allow more flexibility
      - path: _test\.go
        linters:
          - gocyclo
          - cyclop
          - funlen
          - maintidx
          - errcheck
          - gosec
          - goconst
          - dupl
          - gocognit
          - unparam
          - nestif      # Analysis tests have inherent nesting
          - gocritic    # Analysis tests have complex if-else chains

      # Parser - complex by nature
      - path: wgsl/parser\.go
        linters:
          - gocyclo
          - gocognit
          - cyclop
          - funlen
          - maintidx
          - dupl        # constDecl/letDecl are similar by design
          - nestif      # Parsing requires nested conditions
          - gocritic    # Parser has complex if-else chains
          - unparam     # Parser methods have consistent signatures

      # Lexer - similar patterns
      - path: wgsl/lexer\.go
        linters:
          - gocyclo
          - cyclop
          - funlen
          - gocognit
          - nestif
          - gocritic    # Lexer has if-else chains for character matching
          - unparam     # Lexer methods have consistent signatures for future error handling

      # Token - String() method is necessarily complex
      - path: wgsl/token\.go
        linters:
          - gocyclo
          - cyclop

      # CLI tools - file operations and user input are intentional
      - path: cmd/nagac/.*\.go
        linters:
          - gosec       # G304 file inclusion is intentional for CLI

      - path: cmd/spvdis/.*\.go
        linters:
          - gosec       # G703/G705: CLI tool reads user files and prints to stderr

      # SPIR-V backend - int->uint32 conversions are safe for indices
      - path: spirv/.*\.go
        linters:
          - gosec       # G115 int conversions are safe for handle indices
          - maintidx    # Backend emit functions intentionally have low maintainability

      # IR package - int->uint32 conversions are safe for indices
      - path: ir/.*\.go
        linters:
          - gosec       # G115 int conversions are safe for handle indices
          - maintidx    # Validation functions intentionally have low maintainability

      # Shader backend writers - int->uint32 conversions are safe for IR handles
      - path: (glsl|hlsl|msl)/.*\.go
        linters:
          - gosec       # G115 int conversions are safe for handle indices

      # Lowerer - has intentional complexity
      - path: wgsl/lower\.go
        linters:
          - goconst     # "vec" pattern is clearer inline
          - gocritic    # ptrToRefParam: returning *Binding is intentional for optional values
          - gosec       # G115 int conversions safe; G602 slice index guarded by range loop

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
