version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - misspell
    - unconvert

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
