package msl

// reservedWords contains all MSL and C++ reserved words.
// These identifiers must be escaped or renamed when generating MSL code.
var reservedWords = map[string]struct{}{
	// C++ keywords
	"alignas":          {},
	"alignof":          {},
	"and":              {},
	"and_eq":           {},
	"asm":              {},
	"auto":             {},
	"bitand":           {},
	"bitor":            {},
	"bool":             {},
	"break":            {},
	"case":             {},
	"catch":            {},
	"char":             {},
	"char16_t":         {},
	"char32_t":         {},
	"class":            {},
	"compl":            {},
	"const":            {},
	"const_cast":       {},
	"constexpr":        {},
	"continue":         {},
	"decltype":         {},
	"default":          {},
	"delete":           {},
	"do":               {},
	"double":           {},
	"dynamic_cast":     {},
	"else":             {},
	"enum":             {},
	"explicit":         {},
	"export":           {},
	"extern":           {},
	"false":            {},
	"float":            {},
	"for":              {},
	"friend":           {},
	"goto":             {},
	"if":               {},
	"inline":           {},
	"int":              {},
	"long":             {},
	"mutable":          {},
	"namespace":        {},
	"new":              {},
	"noexcept":         {},
	"not":              {},
	"not_eq":           {},
	"nullptr":          {},
	"operator":         {},
	"or":               {},
	"or_eq":            {},
	"private":          {},
	"protected":        {},
	"public":           {},
	"register":         {},
	"reinterpret_cast": {},
	"return":           {},
	"short":            {},
	"signed":           {},
	"sizeof":           {},
	"static":           {},
	"static_assert":    {},
	"static_cast":      {},
	"struct":           {},
	"switch":           {},
	"template":         {},
	"this":             {},
	"thread_local":     {},
	"throw":            {},
	"true":             {},
	"try":              {},
	"typedef":          {},
	"typeid":           {},
	"typename":         {},
	"union":            {},
	"unsigned":         {},
	"using":            {},
	"virtual":          {},
	"void":             {},
	"volatile":         {},
	"wchar_t":          {},
	"while":            {},
	"xor":              {},
	"xor_eq":           {},

	// MSL scalar types
	"char2":     {},
	"char3":     {},
	"char4":     {},
	"uchar":     {},
	"uchar2":    {},
	"uchar3":    {},
	"uchar4":    {},
	"short2":    {},
	"short3":    {},
	"short4":    {},
	"ushort":    {},
	"ushort2":   {},
	"ushort3":   {},
	"ushort4":   {},
	"int2":      {},
	"int3":      {},
	"int4":      {},
	"uint":      {},
	"uint2":     {},
	"uint3":     {},
	"uint4":     {},
	"long2":     {},
	"long3":     {},
	"long4":     {},
	"ulong2":    {},
	"ulong3":    {},
	"ulong4":    {},
	"half":      {},
	"half2":     {},
	"half3":     {},
	"half4":     {},
	"float2":    {},
	"float3":    {},
	"float4":    {},
	"bfloat":    {},
	"bfloat2":   {},
	"bfloat3":   {},
	"bfloat4":   {},
	"size_t":    {},
	"ptrdiff_t": {},

	// MSL packed vector types
	"packed_char2":   {},
	"packed_char3":   {},
	"packed_char4":   {},
	"packed_uchar2":  {},
	"packed_uchar3":  {},
	"packed_uchar4":  {},
	"packed_short2":  {},
	"packed_short3":  {},
	"packed_short4":  {},
	"packed_ushort2": {},
	"packed_ushort3": {},
	"packed_ushort4": {},
	"packed_int2":    {},
	"packed_int3":    {},
	"packed_int4":    {},
	"packed_uint2":   {},
	"packed_uint3":   {},
	"packed_uint4":   {},
	"packed_half2":   {},
	"packed_half3":   {},
	"packed_half4":   {},
	"packed_float2":  {},
	"packed_float3":  {},
	"packed_float4":  {},

	// MSL matrix types
	"float2x2": {},
	"float2x3": {},
	"float2x4": {},
	"float3x2": {},
	"float3x3": {},
	"float3x4": {},
	"float4x2": {},
	"float4x3": {},
	"float4x4": {},
	"half2x2":  {},
	"half2x3":  {},
	"half2x4":  {},
	"half3x2":  {},
	"half3x3":  {},
	"half3x4":  {},
	"half4x2":  {},
	"half4x3":  {},
	"half4x4":  {},

	// MSL address spaces
	"device":      {},
	"constant":    {},
	"thread":      {},
	"threadgroup": {},

	// MSL stage keywords
	"vertex":   {},
	"fragment": {},
	"kernel":   {},

	// MSL atomic types
	"atomic":      {},
	"atomic_int":  {},
	"atomic_uint": {},
	"atomic_bool": {},

	// Metal Shading Language Specification: 6.1 Namespace and Header Files
	"metal": {},

	// Math constants
	"M_E_F":        {},
	"M_LOG2E_F":    {},
	"M_LOG10E_F":   {},
	"M_LN2_F":      {},
	"M_LN10_F":     {},
	"M_PI_F":       {},
	"M_PI_2_F":     {},
	"M_PI_4_F":     {},
	"M_1_PI_F":     {},
	"M_2_PI_F":     {},
	"M_2_SQRTPI_F": {},
	"M_SQRT2_F":    {},
	"M_SQRT1_2_F":  {},
	"INFINITY":     {},
	"NAN":          {},

	// Naga helper function names (reserved to avoid conflicts)
	"naga_div":              {},
	"naga_mod":              {},
	"naga_modf":             {},
	"naga_frexp":            {},
	"naga_atomic_cmp_exch":  {},
	"naga_int_dot":          {},
	"_naga_div":             {},
	"_naga_mod":             {},
	"_naga_modf":            {},
	"_naga_frexp":           {},
	"_naga_atomic_cmp_exch": {},
	"_naga_int_dot":         {},
	"_mslBufferSizes":       {},
	"_buffer_sizes":         {},

	// Metal Shading Language Specification: 1.4.4 Restrictions
	"main": {},
	// Metal Shading Language Specification: 2.20 Type Conversions and Re-interpreting Data
	"as_type": {},
	// Metal reserved types in <metal_types>
	"llong":     {},
	"ullong":    {},
	"quad":      {},
	"complex":   {},
	"imaginary": {},
	// C99 / C++ extension
	"restrict": {},
	// Metal Shading Language Specification: 4 Address Spaces (additional)
	"threadgroup_imageblock": {},
	"ray_data":               {},
	"object_data":            {},

	// Additional MSL types (matching Rust naga keywords.rs)
	"vec":    {},
	"matrix": {},
	"assert": {},

	// MSL sized integer types
	"int8_t":   {},
	"int16_t":  {},
	"int32_t":  {},
	"int64_t":  {},
	"uint8_t":  {},
	"uint16_t": {},
	"uint32_t": {},
	"uint64_t": {},

	// MSL boolean vector types
	"bool2": {},
	"bool3": {},
	"bool4": {},

	// MSL additional atomic types
	"atomic_float": {},
	"atomic_ulong": {},

	// MSL additional packed vector types
	"packed_vec":     {},
	"packed_bool2":   {},
	"packed_bool3":   {},
	"packed_bool4":   {},
	"packed_long2":   {},
	"packed_long3":   {},
	"packed_long4":   {},
	"packed_bfloat2": {},
	"packed_bfloat3": {},
	"packed_bfloat4": {},

	// MSL bounds check helper
	"DefaultConstructible": {},

	// C/C++ limits macros
	"CHAR_BIT":   {},
	"CHAR_MAX":   {},
	"CHAR_MIN":   {},
	"SCHAR_MAX":  {},
	"SCHAR_MIN":  {},
	"UCHAR_MAX":  {},
	"SHRT_MAX":   {},
	"SHRT_MIN":   {},
	"USHRT_MAX":  {},
	"INT_MAX":    {},
	"INT_MIN":    {},
	"UINT_MAX":   {},
	"LONG_MAX":   {},
	"LONG_MIN":   {},
	"ULONG_MAX":  {},
	"LLONG_MAX":  {},
	"LLONG_MIN":  {},
	"ULLONG_MAX": {},

	// Float limits macros
	"FLT_DIG":          {},
	"FLT_MANT_DIG":     {},
	"FLT_MAX_10_EXP":   {},
	"FLT_MAX_EXP":      {},
	"FLT_MIN_10_EXP":   {},
	"FLT_MIN_EXP":      {},
	"FLT_RADIX":        {},
	"FLT_MAX":          {},
	"FLT_MIN":          {},
	"FLT_EPSILON":      {},
	"FLT_DECIMAL_DIG":  {},
	"DBL_DIG":          {},
	"DBL_MANT_DIG":     {},
	"DBL_MAX_10_EXP":   {},
	"DBL_MAX_EXP":      {},
	"DBL_MIN_10_EXP":   {},
	"DBL_MIN_EXP":      {},
	"DBL_RADIX":        {},
	"DBL_MAX":          {},
	"DBL_MIN":          {},
	"DBL_EPSILON":      {},
	"DBL_DECIMAL_DIG":  {},
	"HALF_DIG":         {},
	"HALF_MANT_DIG":    {},
	"HALF_MAX_10_EXP":  {},
	"HALF_MAX_EXP":     {},
	"HALF_MIN_10_EXP":  {},
	"HALF_MIN_EXP":     {},
	"HALF_RADIX":       {},
	"HALF_MAX":         {},
	"HALF_MIN":         {},
	"HALF_EPSILON":     {},
	"HALF_DECIMAL_DIG": {},

	// Float special values
	"HUGE_VAL":    {},
	"HUGE_VALF":   {},
	"HUGE_VALH":   {},
	"MAXFLOAT":    {},
	"MAXHALF":     {},
	"MAXDOUBLE":   {},
	"FP_ILOGB0":   {},
	"FP_ILOGBNAN": {},

	// Math constants (half-precision variants)
	"M_E":          {},
	"M_E_H":        {},
	"M_LOG2E":      {},
	"M_LOG2E_H":    {},
	"M_LOG10E":     {},
	"M_LOG10E_H":   {},
	"M_LN2":        {},
	"M_LN2_H":      {},
	"M_LN10":       {},
	"M_LN10_H":     {},
	"M_PI":         {},
	"M_PI_H":       {},
	"M_PI_2":       {},
	"M_PI_2_H":     {},
	"M_PI_4":       {},
	"M_PI_4_H":     {},
	"M_1_PI":       {},
	"M_1_PI_H":     {},
	"M_2_PI":       {},
	"M_2_PI_H":     {},
	"M_2_SQRTPI":   {},
	"M_2_SQRTPI_H": {},
	"M_SQRT2":      {},
	"M_SQRT2_H":    {},
	"M_SQRT1_2":    {},
	"M_SQRT1_2_H":  {},
}

// isReserved checks if an identifier is a reserved word.
func isReserved(name string) bool {
	_, ok := reservedWords[name]
	return ok
}

// escapeName escapes a name if it's reserved, by adding an underscore suffix.
func escapeName(name string) string {
	if isReserved(name) {
		return name + "_"
	}
	return name
}
