// Copyright 2025 The GoGPU Authors
// SPDX-License-Identifier: MIT

package glsl

import (
	"github.com/gogpu/naga/glsl/internal/codegen"
	"github.com/gogpu/naga/ir"
)

// Version represents a GLSL version.
type Version = codegen.Version

// Common GLSL versions.
var (
	// Desktop OpenGL versions
	Version330 = codegen.Version330 // OpenGL 3.3 Core
	Version400 = codegen.Version400 // OpenGL 4.0
	Version410 = codegen.Version410 // OpenGL 4.1
	Version420 = codegen.Version420 // OpenGL 4.2
	Version430 = codegen.Version430 // OpenGL 4.3 (compute shaders)
	Version450 = codegen.Version450 // OpenGL 4.5
	Version460 = codegen.Version460 // OpenGL 4.6

	// OpenGL ES / WebGL versions
	VersionES300 = codegen.VersionES300 // ES 3.0 / WebGL 2.0
	VersionES310 = codegen.VersionES310 // ES 3.1 (compute shaders)
	VersionES320 = codegen.VersionES320 // ES 3.2
)

// WriterFlags control output formatting.
type WriterFlags = codegen.WriterFlags

// Writer flag constants.
const (
	WriterFlagNone                  = codegen.WriterFlagNone
	WriterFlagExplicitTypes         = codegen.WriterFlagExplicitTypes
	WriterFlagDebugInfo             = codegen.WriterFlagDebugInfo
	WriterFlagMinify                = codegen.WriterFlagMinify
	WriterFlagAdjustCoordinateSpace = codegen.WriterFlagAdjustCoordinateSpace
	WriterFlagForcePointSize        = codegen.WriterFlagForcePointSize
	WriterFlagTextureShadowLod      = codegen.WriterFlagTextureShadowLod
)

// Options configures GLSL code generation.
type Options = codegen.Options

// BindingMapKey identifies a resource binding for the BindingMap.
type BindingMapKey = codegen.BindingMapKey

// BoundsCheckPolicy controls how out-of-bounds resource accesses are handled.
type BoundsCheckPolicy = codegen.BoundsCheckPolicy

// Bounds check policy constants.
const (
	BoundsCheckUnchecked         = codegen.BoundsCheckUnchecked
	BoundsCheckRestrict          = codegen.BoundsCheckRestrict
	BoundsCheckReadZeroSkipWrite = codegen.BoundsCheckReadZeroSkipWrite
)

// BoundsCheckPolicies holds per-resource-type bounds check policies.
type BoundsCheckPolicies = codegen.BoundsCheckPolicies

// TextureMapping describes a combined texture-sampler pair generated by the
// GLSL backend.
type TextureMapping = codegen.TextureMapping

// TranslationInfo contains metadata about the translation.
type TranslationInfo = codegen.TranslationInfo

// DefaultOptions returns sensible default options for GLSL generation.
func DefaultOptions() Options {
	return codegen.DefaultOptions()
}

// Compile generates GLSL source code from an IR module.
// Returns the GLSL source as a string, translation info, or an error.
func Compile(module *ir.Module, options Options) (string, TranslationInfo, error) {
	return codegen.Compile(module, options)
}
